// UI Labels for bilingual support (English / Arabic-Semitic)
// Usage: import { useLabels } from '../hooks/useLabels'; const t = useLabels();

const en = {
  // ── Navigation ────────────────────────────────────────────────
  corpusLibrary:        'Corpus Library',
  graphExploration:     'Graph Exploration',
  positionalRootSearch: 'Positional Root Search',
  lisanLab:             'Lisān Lab & Reports',
  latestUpdates:        'Latest Updates',
  latestReport:         'Latest Report:',
  previousReports:      'Previous Reports',
  latestArticle:        'Latest Article:',
  previousArticles:     'Previous Articles',
  recentDevelopments:   'Recent Developments →',
  acknowledgements:     'Acknowledgements',
  projectOverview:      'Project Overview',
  gettingStarted:       'Getting Started',
  about:                'About',

  // ── Settings panel tabs ───────────────────────────────────────
  general:              'General',
  contexts:             'Contexts',
  filters:              'Filters',
  advancedTypography:   'Advanced Typography Settings',

  // ── PrimaryList / Library ─────────────────────────────────────
  returnToLibrary:      'Return to Library',
  showStatistics:       'Show Statistics',
  loading:              'Loading... Please wait.',
  poetry:               'Poetry',

  // ── Explore ───────────────────────────────────────────────────
  exploreTitle:         'Knowledge Graph Exploration',
  word:                 'Word',
  root:                 'Root',
  form:                 'Form',
  reset:                'Reset',

  // ── Search ────────────────────────────────────────────────────
  searchTitle:          'Advanced Search',
  fullTextSearch:       'Full Text Search',
  fullTextPlaceholder:  'e.g. love, mercy, fear god',
  search:               'Search',
  lanesLexicon:         "Lane's Lexicon",
  hansWehr:             'Hans Wehr',
  wordLabels:           'Word Labels',
  rootSearch:           'Root Search',
  r1:                   'R1:',
  r2:                   'R2:',
  r3:                   'R3:',
  wildcard:             '*',
  noR3:                 'None',
  fetchRoots:           'Fetch Root(s)',
  combinate:            'Combinate',
  fetchExtended:        'Fetch Extended',
  nodeLimit:            'Node Limit:',
  foundWords:           (n) => `Found ${n} words`,
  totalRoots:           (shown, total) => `Total Roots Found: ${total} (Showing ${shown} of ${total})`,
  biradicalOnly:        '(biradical only)',
  twoThreeRadicals:     '(2-3 radicals)',
  patternLabel:         'Pattern:',
  noneLabel:            'None',

  // ── Nodes table ───────────────────────────────────────────────
  colSemantic:          'Semantic',
  colEnglish:           'English',
  colLocation:          'Location',
  itemSingular:         'item',
  itemPlural:           'items',
  noSemantic:           '(no semantic)',
  noEnglish:            '(no english)',

  // ── Node context menu ─────────────────────────────────────────
  moreInfo:             'More info',
  expand:               'Expand',
  collapse:             'Collapse',
  inspectNode:          'Inspect Node',
  reportIssue:          'Report Issue',
  corpusUsage:          'Corpus Usage',
  viewInContext:        'View in Context',
  close:                'Close',

  // ── Node inspector ────────────────────────────────────────────
  inspectorSuffix:      'Inspector',    // "{nodeType} Inspector"
  nodeId:               'ID:',
  addTag:               '+ Tag',
  tagKeyPlaceholder:    'tag_key',
  tagValuePlaceholder:  'value',
  add:                  'Add',
  cancel:               'Cancel',
  saveChanges:          'Save Changes',
  closeInspector:       'Close Inspector',
  properties:           (n) => `Properties (${n})`,
  relationships:        (n) => `Relationships (${n} types)`,
  connectedNodeTypes:   'Connected Node Types',
  noConnectedNodes:     'No connected nodes found',
  summary:              'Summary',
  rawData:              'Raw Data (Advanced)',
  showFullText:         'Show full text',
  saving:               'Saving...',
  empty:                'Empty',
  propertiesLabel:      'Properties:',
  relationshipsLabel:   'Relationships:',
  connectedNodesLabel:  'Connected Nodes:',

  // ── Selectors ─────────────────────────────────────────────────
  l1Label:              'L1:',
  l2Label:              'L2:',
  semitic:              'Semitic',
  english:              'English',
  off:                  'Off',
  guided:               'Guided',
  advanced:             'Advanced',
  corpusLabel:          'Corpus:',
  lexicon:              'Lexicon',
  wordShadeMode:        'Word Shade Mode:',
  none:                 'None',
  grammatical:          'Grammatical',
  ontological:          'Ontological',
  showLinks:            'Show Links',
  showLinkLabels:       'Show Link Labels',
  surahLabel:           'Surah:',
  surahAll:             'All',
  surahNone:            'None',
  surahSelected:        (n) => `${n} selected`,
  morphological:        'Morphological',
  phrase:               'Phrase',
  verb:                 'Verb',
  noun:                 'Noun',
  formNodes:            'Form Nodes',
  additionalSettings:   'Additional Settings',
  wildcardLabel:        'Wildcard',
  addRoot:              'Add Root',
  semiticLanguages:     'Semitic Languages:',
  highlight:            'Highlight:',
  nounsF:               'Nouns (f.)',
  verbs:                'Verbs',
  particles:            'Particles',
  freeformMode:         'Freeform Mode',
  highlightColor:       'Highlight Color:',
  layout:               'Layout:',
  prose:                'Prose',
  lineByLine:           'Line By Line',
  fontSizeLabel:        'Font Size:',
  fontSizeControl:      'Font Size Control',
  formLimit:            (n) => `Form Node Expansion Limit: ${n}`,
  latinText:            'English & Latin Text',
  arabicText:           'Arabic & Semitic Text',
  resetEnglish:         'Reset English',
  resetArabic:          'Reset Arabic',
  resetEnglishTitle:    'Reset English & Latin text to normal size',
  resetArabicTitle:     'Reset Arabic & Semitic text to normal size',
  fontSizePercent:      (n) => `Font size: ${n}%`,
  small:                'Small',
  compactView:          'Compact view',
  normal:               'Normal',
  defaultSize:          'Default size',
  large:                'Large',
  fifteenPercent:       '15% larger',
  extraLarge:           'Extra Large',
  thirtyPercent:        '30% larger',
  xxLarge:              'XX-Large',
  fiftyPercent:         '50% larger',

  // ── InfoBubble ────────────────────────────────────────────────
  loadingAnalysis:      'Loading analysis...',
  failedAnalysis:       'Failed to load analysis',
  concreteOrigin:       'Concrete Origin',
  pathToAbstraction:    'Path to Abstraction',
  fundamentalFrame:     'Fundamental Frame',
  basicStats:           'Basic Stats',
  quranicRefs:          "Qur'anic References",
  hadithRefs:           'Hadith References',
  poeticRefs:           'Poetic References',
  proverbialRefs:       'Proverbial References',
  lexicalSummary:       'Lexical Summary',
  semanticPath:         'Semantic Path',
  wordsExpressions:     'Words & Expressions',
  viewGraph:            'View Graph →',
  viewGraphShort:       'View Graph',
  version:              (v) => `Version ${v}`,
  previousVersions:     (n) => `Previous Versions (${n})`,
  previousVersion:      (v) => `Previous Version: ${v}`,
  versionLabel:         (v) => `Version: ${v}`,

  // ── Settings page ─────────────────────────────────────────────
  typographySettings:   'Typography Settings',
  goToExplore:          'Go to Explore',
  arabicFontStyle:      'Arabic Font Style',
  savedAutomatically:   'Your preferences are saved automatically.',
};

const sem = {
  // ── Navigation ────────────────────────────────────────────────
  corpusLibrary:        'مكتبة النصوص',
  graphExploration:     'الاستكشاف البياني',
  positionalRootSearch: 'بحث الجذور',
  lisanLab:             'مختبر اللسان',
  latestUpdates:        'آخر التحديثات',
  latestReport:         'آخر تقرير:',
  previousReports:      'التقارير السابقة',
  latestArticle:        'آخر مقال:',
  previousArticles:     'المقالات السابقة',
  recentDevelopments:   'آخر المستجدات ←',
  acknowledgements:     'شكر وتقدير',
  projectOverview:      'نظرة عامة',
  gettingStarted:       'للبدء',
  about:                'حول المشروع',

  // ── Settings panel tabs ───────────────────────────────────────
  general:              'عام',
  contexts:             'السياقات',
  filters:              'التصفية',
  advancedTypography:   'إعدادات الخط المتقدمة',

  // ── PrimaryList / Library ─────────────────────────────────────
  returnToLibrary:      'العودة للمكتبة',
  showStatistics:       'إظهار الإحصاء',
  loading:              'جارٍ التحميل...',
  poetry:               'شعر',

  // ── Explore ───────────────────────────────────────────────────
  exploreTitle:         'استكشاف البياني المعرفي',
  word:                 'كلمة',
  root:                 'جذر',
  form:                 'صيغة',
  reset:                'إعادة',

  // ── Search ────────────────────────────────────────────────────
  searchTitle:          'بحث متقدم',
  fullTextSearch:       'بحث نصي كامل',
  fullTextPlaceholder:  'مثال: حب، رحمة، خشية',
  search:               'بحث',
  lanesLexicon:         'معجم لين',
  hansWehr:             'معجم هانز فير',
  wordLabels:           'تسميات الكلمات',
  rootSearch:           'بحث الجذور',
  r1:                   'ج١:',
  r2:                   'ج٢:',
  r3:                   'ج٣:',
  wildcard:             '*',
  noR3:                 'لا شيء',
  fetchRoots:           'جلب الجذور',
  combinate:            'تشكيلات',
  fetchExtended:        'بحث موسّع',
  nodeLimit:            'حد العقد:',
  foundWords:           (n) => `وُجد ${n} كلمة`,
  totalRoots:           (shown, total) => `إجمالي الجذور: ${total} (عرض ${shown} من ${total})`,
  biradicalOnly:        '(ثنائي الجذر)',
  twoThreeRadicals:     '(٢-٣ جذور)',
  patternLabel:         'النمط:',
  noneLabel:            'لا شيء',

  // ── Nodes table ───────────────────────────────────────────────
  colSemantic:          'الدلالة',
  colEnglish:           'الإنجليزية',
  colLocation:          'الموقع',
  itemSingular:         'وحدة',
  itemPlural:           'وحدات',
  noSemantic:           '(لا دلالة)',
  noEnglish:            '(لا ترجمة)',

  // ── Node context menu ─────────────────────────────────────────
  moreInfo:             'مزيد من المعلومات',
  expand:               'توسيع',
  collapse:             'طي',
  inspectNode:          'فحص العقدة',
  reportIssue:          'الإبلاغ عن مشكلة',
  corpusUsage:          'استخدام في النص',
  viewInContext:        'عرض في السياق',
  close:                'إغلاق',

  // ── Node inspector ────────────────────────────────────────────
  inspectorSuffix:      'المفتش',   // "المفتش: {nodeType}"
  nodeId:               'المعرّف:',
  addTag:               '+ وسم',
  tagKeyPlaceholder:    'مفتاح_الوسم',
  tagValuePlaceholder:  'القيمة',
  add:                  'إضافة',
  cancel:               'إلغاء',
  saveChanges:          'حفظ التغييرات',
  closeInspector:       'إغلاق',
  properties:           (n) => `الخصائص (${n})`,
  relationships:        (n) => `العلاقات (${n})`,
  connectedNodeTypes:   'أنواع العقد المرتبطة',
  noConnectedNodes:     'لا توجد عقد مرتبطة',
  summary:              'ملخص',
  rawData:              'البيانات الخام',
  showFullText:         'عرض النص كاملاً',
  saving:               'جارٍ الحفظ...',
  empty:                'فارغ',
  propertiesLabel:      'الخصائص:',
  relationshipsLabel:   'العلاقات:',
  connectedNodesLabel:  'العقد المرتبطة:',

  // ── Selectors ─────────────────────────────────────────────────
  l1Label:              'ل١:',
  l2Label:              'ل٢:',
  semitic:              'السامية',
  english:              'الإنجليزية',
  off:                  'إيقاف',
  guided:               'موجّه',
  advanced:             'متقدم',
  corpusLabel:          'النص:',
  lexicon:              'المعجم',
  wordShadeMode:        'وضع التظليل:',
  none:                 'بلا',
  grammatical:          'نحوي',
  ontological:          'دلالي',
  showLinks:            'إظهار الروابط',
  showLinkLabels:       'تسميات الروابط',
  surahLabel:           'السورة:',
  surahAll:             'الكل',
  surahNone:            'بلا',
  surahSelected:        (n) => `${n} مختار`,
  morphological:        'صرفية',
  phrase:               'عبارة',
  verb:                 'فعل',
  noun:                 'اسم',
  formNodes:            'عقد الصيغ',
  additionalSettings:   'إعدادات إضافية',
  wildcardLabel:        'أي حرف',
  addRoot:              'إضافة جذر',
  semiticLanguages:     'اللغات السامية:',
  highlight:            'إبراز:',
  nounsF:               'أسماء (مؤ.)',
  verbs:                'أفعال',
  particles:            'أدوات',
  freeformMode:         'وضع حر',
  highlightColor:       'لون الإبراز:',
  layout:               'التخطيط:',
  prose:                'نثر',
  lineByLine:           'سطراً بسطر',
  fontSizeLabel:        'حجم الخط:',
  fontSizeControl:      'حجم الخط',
  formLimit:            (n) => `حد توسيع الصيغ: ${n}`,
  latinText:            'النص الإنجليزي',
  arabicText:           'النص العربي',
  resetEnglish:         'إعادة الإنجليزي',
  resetArabic:          'إعادة العربي',
  resetEnglishTitle:    'إعادة ضبط حجم الخط الإنجليزي',
  resetArabicTitle:     'إعادة ضبط حجم الخط العربي',
  fontSizePercent:      (n) => `حجم الخط: ${n}٪`,
  small:                'صغير',
  compactView:          'عرض مضغوط',
  normal:               'عادي',
  defaultSize:          'الحجم الافتراضي',
  large:                'كبير',
  fifteenPercent:       'أكبر بـ ١٥٪',
  extraLarge:           'كبير جداً',
  thirtyPercent:        'أكبر بـ ٣٠٪',
  xxLarge:              'ضخم',
  fiftyPercent:         'أكبر بـ ٥٠٪',

  // ── InfoBubble ────────────────────────────────────────────────
  loadingAnalysis:      'جارٍ التحميل...',
  failedAnalysis:       'فشل التحميل',
  concreteOrigin:       'الأصل الحسّي',
  pathToAbstraction:    'مسار التجريد',
  fundamentalFrame:     'الإطار الأساسي',
  basicStats:           'الإحصاءات',
  quranicRefs:          'الشواهد القرآنية',
  hadithRefs:           'الشواهد الحديثية',
  poeticRefs:           'الشواهد الشعرية',
  proverbialRefs:       'الأمثال',
  lexicalSummary:       'الملخص المعجمي',
  semanticPath:         'المسار الدلالي',
  wordsExpressions:     'الكلمات والتعابير',
  viewGraph:            'عرض البياني ←',
  viewGraphShort:       'عرض البياني',
  version:              (v) => `الإصدار ${v}`,
  previousVersions:     (n) => `إصدارات سابقة (${n})`,
  previousVersion:      (v) => `إصدار سابق: ${v}`,
  versionLabel:         (v) => `الإصدار: ${v}`,

  // ── Settings page ─────────────────────────────────────────────
  typographySettings:   'إعدادات الخط',
  goToExplore:          'إلى الاستكشاف',
  arabicFontStyle:      'نمط الخط العربي',
  savedAutomatically:   'تُحفظ إعداداتك تلقائياً.',
};

export const labels = { en, sem };
